import { useForm } from "react-hook-form";
import { type TenantResponse, type SiteResponse, type HvacFormValues, hvacSchema, Card, Field, Input, Select, Button } from "./Onboarding";
import { zodResolver } from "@hookform/resolvers/zod";

export default function HvacForm({
    busy,
    tenant,
    site,
    onBack,
    onAdd,
    onFinish,
}: {
    busy: boolean;
    tenant: TenantResponse;
    site: SiteResponse;
    onBack: () => void;
    onAdd: (values: HvacFormValues) => Promise<void>;
    onFinish: () => void;
}) {

   const form = useForm<HvacFormValues>({
    resolver: zodResolver(hvacSchema),
    defaultValues: {
      name: "",
      deviceId: "",
      unitType: "OTHER",
      zone: "",
      protocol: "SIMULATED",
    },
  });

  const { register, handleSubmit, reset, formState } = form;
  const { errors, isSubmitting } = formState;


  return (
    <Card
        title="Register HVAC"
        subtitle={`Tenant: ${tenant.name} Site: ${site.siteName}`}
    >

        <form
            className="space-y-4"
            onSubmit={handleSubmit(async (v) => {
            await onAdd(v);
            reset({ ...v, name: "", deviceId: "", zone: "" }); // keep selects, clear text fields
            })}
        >
            <div className="grid gap-4 md:grid-cols-2">
                <Field label="HVAC Name" error={errors.name?.message}>
                    <Input placeholder="e.g., HVAC-1 Lobby" {...register("name")} />
                </Field>

                <Field label="Device ID" error={errors.deviceId?.message}>
                    <Input placeholder="e.g., HVAC-1" {...register("deviceId")} />
                </Field>

                <Field label="Protocol" error={errors.protocol?.message}>
                    <Select {...register("protocol")}>
                        <option value="SIMULATED">Simulated</option>
                        <option value="BACNET">BACnet</option>
                        <option value="MODBUS">Modbus</option>
                    </Select>
                </Field>

                <Field label="Zone / Area (optional)" error={errors.zone?.message as string | undefined}>
                    <Input placeholder="e.g., Floor 2" {...register("zone")} />
                </Field>
            </div>

            <div className="flex flex-wrap items-center justify-between gap-2 pt-2">
          <div className="flex gap-2">
            <Button type="button" variant="secondary" onClick={onBack} disabled={busy || isSubmitting}>
              Back
            </Button>
          </div>

          <div className="flex gap-2">
            <Button type="submit" disabled={busy || isSubmitting}>
              {busy ? "Adding..." : "Add HVAC"}
            </Button>
            <Button type="button" variant="primary" onClick={onFinish}>
              Finish
            </Button>
          </div>
        </div>

        <p className="text-xs text-zinc-500">
          HVAC UUID is generated by backend. deviceId should match your edge-controller/simulator device identifiers.
        </p>
        </form>

    </Card>
  );

}