import { useForm } from 'react-hook-form';
import { tenantSchema, type TenantFormValues, Card, Field, Input, Button } from './Onboarding'
import { zodResolver } from '@hookform/resolvers/zod';

export default function TenantForm({
    busy,
    onSubmit,
}: {
    busy: boolean;
    onSubmit: (values: TenantFormValues) => Promise<void>;
}) {

    const form = useForm<TenantFormValues>({
        resolver: zodResolver(tenantSchema),
        defaultValues: {
            name: "",
            country: "New Zealand",
            addressLine1: "",
            city: "",
            postcode: "",
        }
    });

    const {register, handleSubmit, formState} = form;
    const { errors, isSubmitting } = formState;
    
    return (
        <Card title='Create Tenant' subtitle='Tenant is the top-level account'>
            <form
                className='space-y-4'
                onSubmit={handleSubmit(async (v) => {
                    await onSubmit(v);
                })}
            >

                <div className="grid gap-4 md:grid-cols-2">
                    <Field label="Tenant Name" error={errors.name?.message}>
                        <Input placeholder="e.g., QbitLab Facilities" {...register("name")} />
                    </Field>

                    <Field label="Country" error={errors.country?.message}>
                        <Input placeholder="e.g., New Zealand" {...register("country")} />
                    </Field>

                    <Field label="Address Line 1" error={errors.addressLine1?.message}>
                        <Input placeholder="e.g., 123 Lincoin Road" {...register("addressLine1")} />
                    </Field>

                    <Field label="City" error={errors.city?.message}>
                        <Input placeholder="e.g., Auckland" {...register("city")} />
                    </Field>

                    <Field label="Postcode" error={errors.postcode?.message}>
                        <Input placeholder="e.g., 0612" {...register("postcode")} />
                    </Field>

                    <div className="flex items-center justify-end gap-2 pt-2">
                        <Button type="submit" disabled={busy || isSubmitting}>
                            {busy ? "Creating...." : "Create Tenant"}
                        </Button>
                    </div>

                    <p className="text-xs text-zinc-500">
                        UUID is generated by the backend. UI does not send tenant_id.
                    </p>
                </div>

            </form>
        </Card>
    );
}