import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  type TenantResponse,
  type SiteResponse,
  type HvacFormValues,
  hvacSchema,
} from "./onboarding.types";
import { Card, Field, Input, Select, Button } from "./onboarding.ui";

export default function HvacForm({
  busy,
  tenant,
  site,
  onBack,
  onAdd,
  onFinish,
}: {
  busy: boolean;
  tenant: TenantResponse;
  site: SiteResponse;
  onBack: () => void;
  onAdd: (values: HvacFormValues) => Promise<void>;
  onFinish: () => void;
}) {
  const form = useForm<HvacFormValues>({
    resolver: zodResolver(hvacSchema),
    defaultValues: {
      hvacName: "",
      deviceId: "",
      unitType: "OTHER",
      zone: "",
      protocol: "SIMULATOR",
    },
  });

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting },
  } = form;

  return (
    <Card
      title="Register HVAC"
      subtitle={`Tenant: ${tenant.name} • Site: ${site.siteName}`}
    >
      <form
        className="space-y-5"
        onSubmit={handleSubmit(async (values) => {
          await onAdd(values);
          reset({
            ...values,
            hvacName: "",
            deviceId: "",
            zone: "",
          });
        })}
      >
        <div className="grid gap-4 md:grid-cols-2">
          <Field label="HVAC Name" error={errors.hvacName?.message}>
            <Input placeholder="e.g., HVAC-1 Lobby" {...register("hvacName")} />
          </Field>

          <Field label="Device ID" error={errors.deviceId?.message}>
            <Input placeholder="e.g., hvac-1" {...register("deviceId")} />
          </Field>

          <Field label="Protocol" error={errors.protocol?.message}>
            <Select {...register("protocol")}>
              <option value="SIMULATOR">SIMULATOR</option>
              <option value="BACNET">BACnet</option>
              <option value="MODBUS">Modbus</option>
            </Select>
          </Field>

          <Field label="Unit Type" error={errors.unitType?.message}>
            <Select {...register("unitType")}>
              <option value="OTHER">Other</option>
              <option value="AHU">AHU</option>
              <option value="SPLIT">Split</option>
              <option value="VRF">VRF</option>
              <option value="FAN_COIL">Fan Coil</option>
            </Select>
          </Field>

          <div className="md:col-span-2">
            <Field label="Zone / Area (optional)" error={errors.zone?.message}>
              <Input placeholder="e.g., Floor 2" {...register("zone")} />
            </Field>
          </div>
        </div>

        <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
          <Button type="button" variant="secondary" onClick={onBack} disabled={busy || isSubmitting}>
            Back
          </Button>

          <div className="flex gap-2">
            <Button type="submit" disabled={busy || isSubmitting}>
              {busy || isSubmitting ? "Adding..." : "Add HVAC"}
            </Button>
            <Button type="button" variant="primary" onClick={onFinish}>
              Finish
            </Button>
          </div>
        </div>

        <p className="text-xs text-slate-400">
          HVAC UUID is generated by backend. deviceId should match your edge-controller or simulator device identifiers.
        </p>
      </form>
    </Card>
  );
}