import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { type TenantResponse, type SiteFormValues, siteSchema } from "./onboarding.types";
import { Card, Field, Input, Button } from "./onboarding.ui";

export default function SiteForm({
  busy,
  tenant,
  onBack,
  onSubmit,
}: {
  busy: boolean;
  tenant: TenantResponse;
  onBack: () => void;
  onSubmit: (values: SiteFormValues) => Promise<void>;
}) {
  const form = useForm<SiteFormValues>({
    resolver: zodResolver(siteSchema),
    defaultValues: {
      siteName: "",
      addressLine1: "",
      city: "",
      postcode: "",
      timezone: "Pacific/Auckland",
    },
  });

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = form;

  return (
    <Card
      title="Create Site"
      subtitle={`Tenant: ${tenant.name} • tenantId: ${tenant.tenantId}`}
    >
      <form
        className="space-y-5"
        onSubmit={handleSubmit(async (values) => {
          await onSubmit(values);
        })}
      >
        <div className="grid gap-4 md:grid-cols-2">
          <Field label="Site Name" error={errors.siteName?.message}>
            <Input placeholder="e.g., Auckland Office" {...register("siteName")} />
          </Field>

          <Field label="Timezone" error={errors.timezone?.message}>
            <Input placeholder="e.g., Pacific/Auckland" {...register("timezone")} />
          </Field>

          <Field label="Address Line 1" error={errors.addressLine1?.message}>
            <Input placeholder="e.g., 42 Queen St" {...register("addressLine1")} />
          </Field>

          <Field label="City" error={errors.city?.message}>
            <Input placeholder="e.g., Auckland" {...register("city")} />
          </Field>

          <Field label="Postcode" error={errors.postcode?.message}>
            <Input placeholder="e.g., 1010" {...register("postcode")} />
          </Field>
        </div>

        <div className="flex items-center justify-between gap-3 pt-2">
          <Button type="button" variant="secondary" onClick={onBack} disabled={busy || isSubmitting}>
            Back
          </Button>

          <Button type="submit" disabled={busy || isSubmitting}>
            {busy || isSubmitting ? "Creating..." : "Create Site"}
          </Button>
        </div>

        <p className="text-xs text-slate-400">
          UUID is generated by backend. UI sends only tenantId in the URL path.
        </p>
      </form>
    </Card>
  );
}