import { zodResolver } from "@hookform/resolvers/zod";
import { MapPin } from "lucide-react";
import type { ReactNode } from "react";
import { useForm } from "react-hook-form";

import {
  BmsButton,
  BmsFormModal,
  BmsInput,
} from "@/components/UI";

import {
  type SiteFormValues,
  type TenantResponse,
  siteSchema,
} from "./onboarding.types";

type SiteFormProps = {
  busy: boolean;
  tenant: TenantResponse;
  onBack: () => void;
  onSubmit: (values: SiteFormValues) => Promise<void>;
};

type FormFieldProps = {
  label: string;
  error?: string;
  children: ReactNode;
};

function FormField({ label, error, children }: FormFieldProps) {
  return (
    <label className="block space-y-2">
      <span className="text-sm font-medium text-slate-200">{label}</span>

      {children}

      {error && (
        <span className="block text-xs font-medium text-rose-300">
          {error}
        </span>
      )}
    </label>
  );
}

export default function SiteForm({
  busy,
  tenant,
  onBack,
  onSubmit,
}: SiteFormProps) {
  const form = useForm<SiteFormValues>({
    resolver: zodResolver(siteSchema),
    defaultValues: {
      siteName: "",
      addressLine1: "",
      city: "",
      postcode: "",
      timezone: "Pacific/Auckland",
    },
  });

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = form;

  const disabled = busy || isSubmitting;

  return (
    <BmsFormModal
      open
      eyebrow="SITE SETUP"
      title="Create Site"
      subtitle={`Tenant: ${tenant.name} • tenantId: ${tenant.tenantId}`}
      icon={<MapPin className="h-5 w-5" />}
      onClose={onBack}
    >
      <form
        className="space-y-5"
        onSubmit={handleSubmit(async (values) => {
          await onSubmit(values);
        })}
      >
        <div className="grid gap-4 md:grid-cols-2">
          <FormField label="Site Name" error={errors.siteName?.message}>
            <BmsInput
              placeholder="e.g., Auckland Office"
              disabled={disabled}
              {...register("siteName")}
            />
          </FormField>

          <FormField label="Timezone" error={errors.timezone?.message}>
            <BmsInput
              placeholder="e.g., Pacific/Auckland"
              disabled={disabled}
              {...register("timezone")}
            />
          </FormField>

          <FormField
            label="Address Line 1"
            error={errors.addressLine1?.message}
          >
            <BmsInput
              placeholder="e.g., 42 Queen St"
              disabled={disabled}
              {...register("addressLine1")}
            />
          </FormField>

          <FormField label="City" error={errors.city?.message}>
            <BmsInput
              placeholder="e.g., Auckland"
              disabled={disabled}
              {...register("city")}
            />
          </FormField>

          <FormField label="Postcode" error={errors.postcode?.message}>
            <BmsInput
              placeholder="e.g., 1010"
              disabled={disabled}
              {...register("postcode")}
            />
          </FormField>
        </div>

        <p className="rounded-2xl border border-cyan-400/10 bg-cyan-400/5 px-4 py-3 text-xs leading-5 text-slate-400">
          UUID is generated by backend. UI sends only tenantId in the URL path.
        </p>

        <div className="flex flex-col gap-3 border-t border-white/10 pt-5 sm:flex-row sm:items-center sm:justify-between">
          <BmsButton
            type="button"
            variant="secondary"
            onClick={onBack}
            disabled={disabled}
          >
            Back
          </BmsButton>

          <BmsButton type="submit" variant="primary" disabled={disabled}>
            {busy || isSubmitting ? "Creating..." : "Create Site"}
          </BmsButton>
        </div>
      </form>
    </BmsFormModal>
  );
}