import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { tenantSchema, type TenantFormValues } from "./onboarding.types";
import { Card, Field, Input, Button } from "./onboarding.ui";

export default function TenantForm({
  busy,
  onSubmit,
}: {
  busy: boolean;
  onSubmit: (values: TenantFormValues) => Promise<void>;
}) {
  const form = useForm<TenantFormValues>({
    resolver: zodResolver(tenantSchema),
    defaultValues: {
      name: "",
      country: "New Zealand",
      addressLine1: "",
      city: "",
      postcode: "",
    },
  });

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = form;

  return (
    <Card title="Create Tenant" subtitle="Tenant is the top-level account">
      <form
        className="space-y-5"
        onSubmit={handleSubmit(async (values) => {
          await onSubmit(values);
        })}
      >
        <div className="grid gap-4 md:grid-cols-2">
          <Field label="Tenant Name" error={errors.name?.message}>
            <Input placeholder="e.g., QbitLab Facilities" {...register("name")} />
          </Field>

          <Field label="Country" error={errors.country?.message}>
            <Input placeholder="e.g., New Zealand" {...register("country")} />
          </Field>

          <div className="md:col-span-2">
            <Field label="Address Line 1" error={errors.addressLine1?.message}>
              <Input placeholder="e.g., 123 Lincoln Road" {...register("addressLine1")} />
            </Field>
          </div>

          <Field label="City" error={errors.city?.message}>
            <Input placeholder="e.g., Auckland" {...register("city")} />
          </Field>

          <Field label="Postcode" error={errors.postcode?.message}>
            <Input placeholder="e.g., 0612" {...register("postcode")} />
          </Field>
        </div>

        <div className="flex items-center justify-between gap-3 pt-2">
          <p className="text-xs text-slate-400">
            UUID is generated by the backend. UI does not send tenant_id.
          </p>

          <Button type="submit" disabled={busy || isSubmitting}>
            {busy || isSubmitting ? "Creating..." : "Create Tenant"}
          </Button>
        </div>
      </form>
    </Card>
  );
}