import { zodResolver } from "@hookform/resolvers/zod";
import type { ReactNode } from "react";
import { useForm } from "react-hook-form";

import { BmsButton, BmsCard, BmsInput } from "@/components/UI";

import { tenantSchema, type TenantFormValues } from "./onboarding.types";

type TenantFormProps = {
  busy: boolean;
  onSubmit: (values: TenantFormValues) => Promise<void>;
};

type FormFieldProps = {
  label: string;
  error?: string;
  children: ReactNode;
};

function FormField({ label, error, children }: FormFieldProps) {
  return (
    <label className="block space-y-2">
      <span className="text-sm font-medium text-slate-200">{label}</span>

      {children}

      {error && (
        <span className="block text-xs font-medium text-rose-300">
          {error}
        </span>
      )}
    </label>
  );
}

export default function TenantForm({ busy, onSubmit }: TenantFormProps) {
  const form = useForm<TenantFormValues>({
    resolver: zodResolver(tenantSchema),
    defaultValues: {
      name: "",
      country: "New Zealand",
      addressLine1: "",
      city: "",
      postcode: "",
    },
  });

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = form;

  const disabled = busy || isSubmitting;

  return (
    <BmsCard variant="section" className="p-5">
      <div className="mb-5 border-b border-white/10 pb-4">
        <p className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-200/80">
          Tenant setup
        </p>

        <h2 className="mt-1 text-xl font-semibold text-white">
          Create Tenant
        </h2>

        <p className="mt-1 text-sm text-slate-400">
          Tenant is the top-level account.
        </p>
      </div>

      <form
        className="space-y-5"
        onSubmit={handleSubmit(async (values) => {
          await onSubmit(values);
        })}
      >
        <div className="grid gap-4 md:grid-cols-2">
          <FormField label="Tenant Name" error={errors.name?.message}>
            <BmsInput
              placeholder="e.g., QbitLab Facilities"
              disabled={disabled}
              {...register("name")}
            />
          </FormField>

          <FormField label="Country" error={errors.country?.message}>
            <BmsInput
              placeholder="e.g., New Zealand"
              disabled={disabled}
              {...register("country")}
            />
          </FormField>

          <div className="md:col-span-2">
            <FormField
              label="Address Line 1"
              error={errors.addressLine1?.message}
            >
              <BmsInput
                placeholder="e.g., 123 Lincoln Road"
                disabled={disabled}
                {...register("addressLine1")}
              />
            </FormField>
          </div>

          <FormField label="City" error={errors.city?.message}>
            <BmsInput
              placeholder="e.g., Auckland"
              disabled={disabled}
              {...register("city")}
            />
          </FormField>

          <FormField label="Postcode" error={errors.postcode?.message}>
            <BmsInput
              placeholder="e.g., 0612"
              disabled={disabled}
              {...register("postcode")}
            />
          </FormField>
        </div>

        <div className="flex flex-col gap-3 border-t border-white/10 pt-5 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-xs leading-5 text-slate-400">
            UUID is generated by the backend. UI does not send tenant_id.
          </p>

          <BmsButton type="submit" variant="primary" disabled={disabled}>
            {busy || isSubmitting ? "Creating..." : "Create Tenant"}
          </BmsButton>
        </div>
      </form>
    </BmsCard>
  );
}