/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState } from "react";
import {
  AlertCircle,
  CheckCircle2,
  Cpu,
  RefreshCw,
  Save,
  Sparkles,
  X,
} from "lucide-react";

import {
  BmsApi,
  type HvacDeviceMappingDto,
  type HvacPointMappingProtocol,
  type HvacPointMappingRequest,
  type HvacPointMappingResponse,
} from "@/api/bms";

type SupportedProtocol =
  | HvacPointMappingProtocol
  | "SIMULATOR"
  | "BACNET"
  | "MODBUS"
  | "MODBUS_TCP"
  | "MODBUS_RTU";

type Props = {
  tenantId: string;
  siteId: string;
  mapping: HvacDeviceMappingDto;
  edgeControllerId?: string | null;
  protocol?: SupportedProtocol;
  onClose: () => void;
  onSaved?: () => void;
};

const DEFAULT_SIMULATOR_POINTS = {
  temperaturePoint: "simulator.temperature",
  setpointPoint: "simulator.setpoint",
  onoffPoint: "simulator.on_state",
  fanSpeedPoint: "simulator.fan_speed",
  flowRatePoint: "simulator.flow_rate",
  faultPoint: "simulator.fault",
  ambientTempPoint: "simulator.ambient_temperature",
};

const DEFAULT_BACNET_POINTS = {
  temperaturePoint: "analogInput:1",
  setpointPoint: "analogValue:2",
  onoffPoint: "binaryValue:1",
  fanSpeedPoint: "multiStateValue:3",
  flowRatePoint: "analogInput:5",
  faultPoint: "binaryInput:4",
  ambientTempPoint: "analogInput:6",
};

const DEFAULT_MODBUS_TCP_POINTS = {
  temperaturePoint: "inputRegister:30001",
  setpointPoint: "holdingRegister:40001",
  onoffPoint: "coil:1",
  fanSpeedPoint: "holdingRegister:40002",
  flowRatePoint: "inputRegister:30002",
  faultPoint: "discreteInput:1",
  ambientTempPoint: "inputRegister:30003",
};

const DEFAULT_MODBUS_RTU_PT100_POINTS = {
  temperaturePoint: "inputRegister:1:int16:scale=0.1",
  setpointPoint: "",
  onoffPoint: "",
  fanSpeedPoint: "",
  flowRatePoint: "",
  faultPoint: "",
  ambientTempPoint: "",
};

function cleanProtocol(value?: string | null): SupportedProtocol {
  const protocol = (value || "SIMULATOR").trim().toUpperCase();

  if (protocol === "BACNET") return "BACNET";
  if (protocol === "MODBUS") return "MODBUS";
  if (protocol === "MODBUS_TCP") return "MODBUS_TCP";
  if (protocol === "MODBUS_RTU") return "MODBUS_RTU";

  return "SIMULATOR";
}

function protocolForRequest(protocol: SupportedProtocol): HvacPointMappingProtocol {
  return cleanProtocol(protocol) as HvacPointMappingProtocol;
}

function getDefaultPointsForProtocol(protocol: SupportedProtocol) {
  const p = cleanProtocol(protocol);

  if (p === "BACNET") return DEFAULT_BACNET_POINTS;
  if (p === "MODBUS" || p === "MODBUS_TCP") return DEFAULT_MODBUS_TCP_POINTS;
  if (p === "MODBUS_RTU") return DEFAULT_MODBUS_RTU_PT100_POINTS;

  return DEFAULT_SIMULATOR_POINTS;
}

function getDefaultWritableForProtocol(protocol: SupportedProtocol) {
  const p = cleanProtocol(protocol);

  if (p === "SIMULATOR") {
    return {
      writableSetpoint: true,
      writableOnoff: true,
      writableFanSpeed: true,
      writableFlowRate: true,
      writableRestart: false,
    };
  }

  if (p === "MODBUS_RTU") {
    return {
      writableSetpoint: false,
      writableOnoff: false,
      writableFanSpeed: false,
      writableFlowRate: false,
      writableRestart: false,
    };
  }

  return {
    writableSetpoint: true,
    writableOnoff: true,
    writableFanSpeed: false,
    writableFlowRate: false,
    writableRestart: false,
  };
}

function getProtocolInfo(protocol: SupportedProtocol) {
  const p = cleanProtocol(protocol);

  if (p === "BACNET") {
    return {
      title: "BACnet point references",
      description:
        "Use BACnet object refs from scanner results. Example: analogInput:1 or binaryValue:1.",
      examples: [
        "Temperature: analogInput:1",
        "Setpoint: analogValue:2",
        "On/Off: binaryValue:1",
        "Fault: binaryInput:4",
      ],
    };
  }

  if (p === "MODBUS" || p === "MODBUS_TCP") {
    return {
      title: "Modbus TCP register/coil references",
      description:
        "Use Modbus TCP references from scanner/register map. Example: holdingRegister:40001 or coil:1.",
      examples: [
        "Temperature: inputRegister:30001",
        "Setpoint: holdingRegister:40001",
        "On/Off: coil:1",
        "Fault: discreteInput:1",
      ],
    };
  }

  if (p === "MODBUS_RTU") {
    return {
      title: "Modbus RTU / PT100 point references",
      description:
        "Use Modbus RTU point refs from the real serial sensor. PT100 is read-only, so only temperature should be mapped.",
      examples: [
        "Temperature: inputRegister:1:int16:scale=0.1",
        "Slave/unit id is configured in edge-device-config.yml",
        "Leave setpoint, on/off, fan, flow, fault empty for PT100",
        "All writable flags should be unchecked",
      ],
    };
  }

  return {
    title: "Simulator point references",
    description:
      "Use simulator point refs generated by QbitLabs edge simulator.",
    examples: [
      "Temperature: simulator.temperature",
      "Setpoint: simulator.setpoint",
      "On/Off: simulator.on_state",
      "Fault: simulator.fault",
    ],
  };
}

function buildDefaultForm(
  mapping: HvacDeviceMappingDto,
  edgeControllerId?: string | null,
  protocol: SupportedProtocol = "SIMULATOR"
): HvacPointMappingRequest {
  const clean = cleanProtocol(protocol);
  const points = getDefaultPointsForProtocol(clean);
  const writable = getDefaultWritableForProtocol(clean);

  return {
    edgeControllerId: edgeControllerId ?? null,
    protocol: protocolForRequest(clean),
    externalDeviceId: mapping.externalDeviceId,
    unitName: mapping.unitName || mapping.externalDeviceId,

    temperaturePoint: points.temperaturePoint,
    setpointPoint: points.setpointPoint,
    onoffPoint: points.onoffPoint,
    fanSpeedPoint: points.fanSpeedPoint,
    flowRatePoint: points.flowRatePoint,
    faultPoint: points.faultPoint,
    ambientTempPoint: points.ambientTempPoint,

    ...writable,

    minSetpoint: 16,
    maxSetpoint: 30,
    enabled: true,
  };
}

function responseToForm(
  response: HvacPointMappingResponse,
  fallback: HvacPointMappingRequest
): HvacPointMappingRequest {
  const protocol = cleanProtocol(response.protocol ?? fallback.protocol);

  return {
    edgeControllerId: response.edgeControllerId ?? fallback.edgeControllerId,
    protocol: protocolForRequest(protocol),
    externalDeviceId: response.externalDeviceId ?? fallback.externalDeviceId,
    unitName: response.unitName ?? fallback.unitName,

    temperaturePoint: response.temperaturePoint ?? "",
    setpointPoint: response.setpointPoint ?? "",
    onoffPoint: response.onoffPoint ?? "",
    fanSpeedPoint: response.fanSpeedPoint ?? "",
    flowRatePoint: response.flowRatePoint ?? "",
    faultPoint: response.faultPoint ?? "",
    ambientTempPoint: response.ambientTempPoint ?? "",

    writableSetpoint: response.writableSetpoint ?? fallback.writableSetpoint,
    writableOnoff: response.writableOnoff ?? fallback.writableOnoff,
    writableFanSpeed: response.writableFanSpeed ?? fallback.writableFanSpeed,
    writableFlowRate: response.writableFlowRate ?? fallback.writableFlowRate,
    writableRestart: response.writableRestart ?? fallback.writableRestart,

    minSetpoint: response.minSetpoint ?? fallback.minSetpoint,
    maxSetpoint: response.maxSetpoint ?? fallback.maxSetpoint,
    enabled: response.enabled ?? fallback.enabled,
  };
}

export default function HvacPointMappingPanel({
  tenantId,
  siteId,
  mapping,
  edgeControllerId,
  protocol = "SIMULATOR",
  onClose,
  onSaved,
}: Props) {
  const defaultForm = useMemo(
    () => buildDefaultForm(mapping, edgeControllerId, protocol),
    [mapping, edgeControllerId, protocol]
  );

  const [form, setForm] = useState<HvacPointMappingRequest>(defaultForm);
  const [existing, setExisting] = useState<HvacPointMappingResponse | null>(null);

  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  const currentProtocol = cleanProtocol(form.protocol);
  const isSimulator = currentProtocol === "SIMULATOR";
  const isModbusRtu = currentProtocol === "MODBUS_RTU";
  const protocolInfo = getProtocolInfo(currentProtocol);

  const updateField = <K extends keyof HvacPointMappingRequest>(
    key: K,
    value: HvacPointMappingRequest[K]
  ) => {
    setForm((prev) => ({
      ...prev,
      [key]: value,
    }));
  };

  const applyProtocolTemplate = (nextProtocolValue: string) => {
    const nextProtocol = cleanProtocol(nextProtocolValue);
    const points = getDefaultPointsForProtocol(nextProtocol);
    const writable = getDefaultWritableForProtocol(nextProtocol);

    setForm((prev) => ({
      ...prev,
      protocol: protocolForRequest(nextProtocol),

      temperaturePoint: points.temperaturePoint,
      setpointPoint: points.setpointPoint,
      onoffPoint: points.onoffPoint,
      fanSpeedPoint: points.fanSpeedPoint,
      flowRatePoint: points.flowRatePoint,
      faultPoint: points.faultPoint,
      ambientTempPoint: points.ambientTempPoint,

      ...writable,
    }));

    setSuccessMessage(
      `${nextProtocol} template applied. Review point refs before saving.`
    );

    window.setTimeout(() => {
      setSuccessMessage(null);
    }, 2500);
  };

  const loadPointMapping = async () => {
    setLoading(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      const data = await BmsApi.getHvacPointMapping(
        tenantId,
        siteId,
        mapping.hvacId
      );

      if (!data) {
        setExisting(null);
        setForm(defaultForm);
        return;
      }

      setExisting(data);
      setForm(responseToForm(data, defaultForm));
    } catch (error: any) {
      const status = error?.response?.status;

      if (status === 204 || status === 404) {
        setExisting(null);
        setForm(defaultForm);
      } else {
        setErrorMessage(
          error?.response?.data?.message ||
            error?.message ||
            "Failed to load point mapping."
        );
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void loadPointMapping();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tenantId, siteId, mapping.hvacId]);

  const saveManual = async () => {
    setSaving(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      const saved = await BmsApi.upsertHvacPointMapping(
        tenantId,
        siteId,
        mapping.hvacId,
        form
      );

      setExisting(saved);
      setForm(responseToForm(saved, form));
      setSuccessMessage("Point mapping saved successfully.");
      onSaved?.();
    } catch (error: any) {
      setErrorMessage(
        error?.response?.data?.message ||
          error?.message ||
          "Failed to save point mapping."
      );
    } finally {
      setSaving(false);
    }
  };

  const createSimulatorDefaults = async () => {
    if (!edgeControllerId) {
      setErrorMessage("Edge controller assignment is missing for this site.");
      return;
    }

    setSaving(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      const saved = await BmsApi.createSimulatorPointMappingDefaults(
        tenantId,
        siteId,
        mapping.hvacId,
        {
          edgeControllerId,
          externalDeviceId: mapping.externalDeviceId,
          unitName: mapping.unitName || mapping.externalDeviceId,
        }
      );

      setExisting(saved);
      setForm(responseToForm(saved, buildDefaultForm(mapping, edgeControllerId, "SIMULATOR")));
      setSuccessMessage("Simulator point defaults created successfully.");
      onSaved?.();
    } catch (error: any) {
      setErrorMessage(
        error?.response?.data?.message ||
          error?.message ||
          "Failed to create simulator defaults."
      );
    } finally {
      setSaving(false);
    }
  };

  const deletePointMapping = async () => {
    if (!window.confirm("Delete point mapping for this HVAC?")) {
      return;
    }

    setSaving(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      await BmsApi.deleteHvacPointMapping(tenantId, siteId, mapping.hvacId);
      setExisting(null);
      setForm(defaultForm);
      setSuccessMessage("Point mapping deleted.");
      onSaved?.();
    } catch (error: any) {
      setErrorMessage(
        error?.response?.data?.message ||
          error?.message ||
          "Failed to delete point mapping."
      );
    } finally {
      setSaving(false);
    }
  };

  const pointRows: Array<{
    label: string;
    field: keyof HvacPointMappingRequest;
    simulator: string;
    bacnet: string;
    modbus: string;
    modbusRtu: string;
    hint: string;
  }> = [
    {
      label: "Temperature",
      field: "temperaturePoint",
      simulator: "simulator.temperature",
      bacnet: "analogInput:1",
      modbus: "inputRegister:30001",
      modbusRtu: "inputRegister:1:int16:scale=0.1",
      hint: "Read-only measured temperature",
    },
    {
      label: "Setpoint",
      field: "setpointPoint",
      simulator: "simulator.setpoint",
      bacnet: "analogValue:2",
      modbus: "holdingRegister:40001",
      modbusRtu: "",
      hint: "Writable command point. Leave empty for PT100.",
    },
    {
      label: "On / Off",
      field: "onoffPoint",
      simulator: "simulator.on_state",
      bacnet: "binaryValue:1",
      modbus: "coil:1",
      modbusRtu: "",
      hint: "Writable enable/disable point. Leave empty for PT100.",
    },
    {
      label: "Fan Speed",
      field: "fanSpeedPoint",
      simulator: "simulator.fan_speed",
      bacnet: "multiStateValue:3",
      modbus: "holdingRegister:40002",
      modbusRtu: "",
      hint: "Writable only if verified. Leave empty for PT100.",
    },
    {
      label: "Flow Rate",
      field: "flowRatePoint",
      simulator: "simulator.flow_rate",
      bacnet: "analogInput:5",
      modbus: "inputRegister:30002",
      modbusRtu: "",
      hint: "Usually read-only for real devices. Leave empty for PT100.",
    },
    {
      label: "Fault",
      field: "faultPoint",
      simulator: "simulator.fault",
      bacnet: "binaryInput:4",
      modbus: "discreteInput:1",
      modbusRtu: "",
      hint: "Read-only fault status. Leave empty for PT100 unless verified.",
    },
    {
      label: "Ambient Temp",
      field: "ambientTempPoint",
      simulator: "simulator.ambient_temperature",
      bacnet: "analogInput:6",
      modbus: "inputRegister:30003",
      modbusRtu: "",
      hint: "Optional ambient/reference temperature. Leave empty for PT100.",
    },
  ];

  const placeholderFor = (row: (typeof pointRows)[number]) => {
    if (currentProtocol === "BACNET") return row.bacnet;
    if (currentProtocol === "MODBUS" || currentProtocol === "MODBUS_TCP") return row.modbus;
    if (currentProtocol === "MODBUS_RTU") return row.modbusRtu;
    return row.simulator;
  };

  return (
    <section className="rounded-3xl border border-cyan-400/20 bg-slate-950/80 p-5 shadow-[0_18px_70px_rgba(8,47,73,0.45)] backdrop-blur-xl">
      <div className="mb-5 flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
        <div>
          <div className="flex items-center gap-2 text-sm font-semibold uppercase tracking-[0.2em] text-cyan-300">
            <Cpu className="h-4 w-4" />
            Point Mapping
          </div>

          <h2 className="mt-2 text-2xl font-bold text-white">
            {mapping.hvacName || "Mapped HVAC"}
          </h2>

          <p className="mt-2 text-sm text-slate-400">
            Map QbitLabs fields to simulator, BACnet, Modbus TCP, or Modbus RTU points.
          </p>

          <div className="mt-3 grid gap-2 text-xs text-slate-400 md:grid-cols-2">
            <div>
              <span className="text-slate-300">External Device:</span>{" "}
              {mapping.externalDeviceId}
            </div>
            <div>
              <span className="text-slate-300">Unit:</span>{" "}
              {mapping.unitName || "-"}
            </div>
            <div>
              <span className="text-slate-300">HVAC ID:</span> {mapping.hvacId}
            </div>
            <div>
              <span className="text-slate-300">Edge:</span>{" "}
              {edgeControllerId || "Not assigned"}
            </div>
          </div>
        </div>

        <button
          type="button"
          onClick={onClose}
          className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-semibold text-slate-200 transition hover:bg-white/10"
        >
          <X className="h-4 w-4" />
          Close
        </button>
      </div>

      {errorMessage && (
        <div className="mb-4 flex items-start gap-3 rounded-2xl border border-rose-500/20 bg-rose-500/10 px-4 py-3 text-sm font-medium text-rose-300">
          <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{errorMessage}</span>
        </div>
      )}

      {successMessage && (
        <div className="mb-4 flex items-start gap-3 rounded-2xl border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm font-medium text-emerald-300">
          <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" />
          <span>{successMessage}</span>
        </div>
      )}

      {loading ? (
        <div className="rounded-2xl border border-white/10 bg-white/5 p-6 text-center text-sm text-slate-400">
          Loading point mapping...
        </div>
      ) : (
        <div className="space-y-5">
          <div className="rounded-3xl border border-cyan-400/20 bg-cyan-500/10 p-4">
            <div className="text-sm font-semibold text-cyan-200">
              {protocolInfo.title}
            </div>
            <p className="mt-1 text-sm text-slate-300">
              {protocolInfo.description}
            </p>
            <div className="mt-3 grid gap-2 text-xs text-slate-400 md:grid-cols-2">
              {protocolInfo.examples.map((example) => (
                <div
                  key={example}
                  className="rounded-2xl border border-white/10 bg-slate-950/50 px-3 py-2"
                >
                  {example}
                </div>
              ))}
            </div>
          </div>

          {isModbusRtu && (
            <div className="rounded-2xl border border-amber-400/20 bg-amber-500/10 px-4 py-3 text-sm text-amber-100">
              PT100 Modbus RTU is read-only. Keep only the temperature point filled:
              <span className="ml-1 font-semibold">
                inputRegister:1:int16:scale=0.1
              </span>
              . Leave command points empty and keep writable flags unchecked.
            </div>
          )}

          <div className="grid gap-4 md:grid-cols-4">
            <div>
              <label className="mb-1 block text-xs font-semibold text-slate-300">
                Protocol
              </label>
              <select
                value={currentProtocol}
                onChange={(event) => applyProtocolTemplate(event.target.value)}
                className="w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition focus:border-cyan-400/60"
              >
                <option value="SIMULATOR">SIMULATOR</option>
                <option value="BACNET">BACNET</option>
                <option value="MODBUS">MODBUS</option>
                <option value="MODBUS_TCP">MODBUS_TCP</option>
                <option value="MODBUS_RTU">MODBUS_RTU</option>
              </select>
            </div>

            <div>
              <label className="mb-1 block text-xs font-semibold text-slate-300">
                Min Setpoint
              </label>
              <input
                type="number"
                value={form.minSetpoint ?? ""}
                onChange={(event) =>
                  updateField(
                    "minSetpoint",
                    event.target.value === "" ? null : Number(event.target.value)
                  )
                }
                disabled={isModbusRtu}
                className="w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition focus:border-cyan-400/60 disabled:cursor-not-allowed disabled:opacity-50"
              />
            </div>

            <div>
              <label className="mb-1 block text-xs font-semibold text-slate-300">
                Max Setpoint
              </label>
              <input
                type="number"
                value={form.maxSetpoint ?? ""}
                onChange={(event) =>
                  updateField(
                    "maxSetpoint",
                    event.target.value === "" ? null : Number(event.target.value)
                  )
                }
                disabled={isModbusRtu}
                className="w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition focus:border-cyan-400/60 disabled:cursor-not-allowed disabled:opacity-50"
              />
            </div>

            <label className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-200">
              <input
                type="checkbox"
                checked={Boolean(form.enabled)}
                onChange={(event) => updateField("enabled", event.target.checked)}
              />
              Enabled
            </label>
          </div>

          <div className="overflow-x-auto rounded-3xl border border-white/10">
            <table className="min-w-full border-separate border-spacing-0">
              <thead>
                <tr className="bg-white/5 text-left text-sm text-slate-300">
                  <th className="px-4 py-3 font-semibold">QbitLabs Field</th>
                  <th className="px-4 py-3 font-semibold">Source Point Ref</th>
                  <th className="px-4 py-3 font-semibold">Note</th>
                </tr>
              </thead>

              <tbody>
                {pointRows.map((row, index) => (
                  <tr
                    key={row.field}
                    className={index % 2 === 0 ? "bg-slate-950/10" : "bg-white/5"}
                  >
                    <td className="px-4 py-3 text-sm font-medium text-slate-100">
                      {row.label}
                    </td>

                    <td className="px-4 py-3">
                      <input
                        value={String(form[row.field] ?? "")}
                        onChange={(event) =>
                          updateField(row.field, event.target.value as any)
                        }
                        placeholder={placeholderFor(row)}
                        className="w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition placeholder:text-slate-600 focus:border-cyan-400/60"
                      />
                    </td>

                    <td className="px-4 py-3 text-xs text-slate-400">
                      {row.hint}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="grid gap-3 md:grid-cols-5">
            <label className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-200">
              <input
                type="checkbox"
                checked={Boolean(form.writableSetpoint)}
                disabled={isModbusRtu}
                onChange={(event) =>
                  updateField("writableSetpoint", event.target.checked)
                }
              />
              Setpoint writable
            </label>

            <label className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-200">
              <input
                type="checkbox"
                checked={Boolean(form.writableOnoff)}
                disabled={isModbusRtu}
                onChange={(event) =>
                  updateField("writableOnoff", event.target.checked)
                }
              />
              On/off writable
            </label>

            <label className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-200">
              <input
                type="checkbox"
                checked={Boolean(form.writableFanSpeed)}
                disabled={isModbusRtu}
                onChange={(event) =>
                  updateField("writableFanSpeed", event.target.checked)
                }
              />
              Fan writable
            </label>

            <label className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-200">
              <input
                type="checkbox"
                checked={Boolean(form.writableFlowRate)}
                disabled={isModbusRtu}
                onChange={(event) =>
                  updateField("writableFlowRate", event.target.checked)
                }
              />
              Flow writable
            </label>

            <label className="flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-200">
              <input
                type="checkbox"
                checked={Boolean(form.writableRestart)}
                disabled={isModbusRtu}
                onChange={(event) =>
                  updateField("writableRestart", event.target.checked)
                }
              />
              Restart writable
            </label>
          </div>

          <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div className="text-xs text-slate-500">
              {existing ? (
                <span>
                  Existing mapping found. Config version:{" "}
                  <span className="text-slate-300">
                    {existing.configVersion ?? "-"}
                  </span>
                </span>
              ) : (
                <span>No point mapping saved yet.</span>
              )}
            </div>

            <div className="flex flex-wrap gap-3">
              {isSimulator && (
                <button
                  type="button"
                  onClick={() => void createSimulatorDefaults()}
                  disabled={saving}
                  className="inline-flex items-center gap-2 rounded-2xl border border-cyan-400/30 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 transition hover:bg-cyan-500/20 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  <Sparkles className="h-4 w-4" />
                  Simulator Defaults
                </button>
              )}

              <button
                type="button"
                onClick={() => void loadPointMapping()}
                disabled={saving}
                className="inline-flex items-center gap-2 rounded-2xl border border-white/10 bg-white/5 px-4 py-2 text-sm font-semibold text-slate-200 transition hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-60"
              >
                <RefreshCw className="h-4 w-4" />
                Reload
              </button>

              {existing && (
                <button
                  type="button"
                  onClick={() => void deletePointMapping()}
                  disabled={saving}
                  className="inline-flex items-center gap-2 rounded-2xl border border-rose-400/30 bg-rose-500/10 px-4 py-2 text-sm font-semibold text-rose-200 transition hover:bg-rose-500/20 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  Delete Points
                </button>
              )}

              <button
                type="button"
                onClick={() => void saveManual()}
                disabled={saving}
                className="inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-blue-500 to-purple-500 px-5 py-2 text-sm font-semibold text-white transition hover:scale-[1.02] disabled:cursor-not-allowed disabled:opacity-60"
              >
                <Save className="h-4 w-4" />
                {saving ? "Saving..." : "Save Mapping"}
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  );
}