/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import {
  AlertCircle,
  ArrowLeft,
  CheckCircle2,
  //Cpu,
  DatabaseZap,
  Loader2,
  //PlugZap,
  RefreshCw,
  Save,
  Sparkles,
  Trash2,
  //Zap,
} from "lucide-react";
import { motion } from "framer-motion";

import { api } from "@/api/http";

type EnergyProtocol = "SIMULATOR" | "BACNET" | "MODBUS";

type EnergyPointMappingRequest = {
  protocol: EnergyProtocol;
  externalDeviceId: string;
  meterName: string;
  activePowerKwPoint: string;
  totalEnergyKwhPoint: string;
  voltagePoint: string;
  currentAmpPoint: string;
  powerFactorPoint: string;
  frequencyHzPoint: string;
  baselinePowerKw: number | null;
  ratedPowerKw: number | null;
  enabled: boolean;
};

type EnergyPointMappingResponse = EnergyPointMappingRequest & {
  energyMeterId?: string;
  energyMeterPointMappingId?: string;
  configVersion?: number;
  createdAt?: string;
  updatedAt?: string;
};

type LocationState = {
  meterName?: string;
  externalDeviceId?: string;
  protocol?: string;
};

const DEFAULT_SIMULATOR_POINTS = {
  activePowerKwPoint: "simulator.active_power_kw",
  totalEnergyKwhPoint: "simulator.total_energy_kwh",
  voltagePoint: "simulator.voltage",
  currentAmpPoint: "simulator.current_amp",
  powerFactorPoint: "simulator.power_factor",
  frequencyHzPoint: "simulator.frequency_hz",
};

const DEFAULT_BACNET_POINTS = {
  activePowerKwPoint: "analogInput:1",
  totalEnergyKwhPoint: "analogInput:2",
  voltagePoint: "analogInput:3",
  currentAmpPoint: "analogInput:4",
  powerFactorPoint: "analogInput:5",
  frequencyHzPoint: "analogInput:6",
};

const DEFAULT_MODBUS_POINTS = {
  activePowerKwPoint: "inputRegister:30001:float32",
  totalEnergyKwhPoint: "inputRegister:30003:float32",
  voltagePoint: "inputRegister:30005:float32",
  currentAmpPoint: "inputRegister:30007:float32",
  powerFactorPoint: "inputRegister:30009:float32",
  frequencyHzPoint: "inputRegister:30011:float32",
};

function cleanProtocol(value?: string | null): EnergyProtocol {
  const protocol = (value || "SIMULATOR").trim().toUpperCase();

  if (protocol === "BACNET") return "BACNET";
  if (protocol === "MODBUS") return "MODBUS";

  return "SIMULATOR";
}

function getDefaultPoints(protocol: EnergyProtocol) {
  if (protocol === "BACNET") return DEFAULT_BACNET_POINTS;
  if (protocol === "MODBUS") return DEFAULT_MODBUS_POINTS;
  return DEFAULT_SIMULATOR_POINTS;
}

function getProtocolInfo(protocol: EnergyProtocol) {
  if (protocol === "BACNET") {
    return {
      title: "BACnet Energy Meter points",
      description:
        "Use BACnet object references from the meter/device manual or scanner result.",
      examples: [
        "Active Power: analogInput:1",
        "Total Energy: analogInput:2",
        "Voltage: analogInput:3",
        "Current: analogInput:4",
      ],
    };
  }

  if (protocol === "MODBUS") {
    return {
      title: "Modbus Energy Meter registers",
      description:
        "Use Modbus register references from the energy meter register map.",
      examples: [
        "Active Power: inputRegister:30001:float32",
        "Total Energy: inputRegister:30003:float32",
        "Voltage: inputRegister:30005:float32",
        "Current: inputRegister:30007:float32",
      ],
    };
  }

  return {
    title: "Simulator Energy Meter points",
    description:
      "Use QbitLabs simulator points generated by the Python Edge Controller.",
    examples: [
      "Active Power: simulator.active_power_kw",
      "Total Energy: simulator.total_energy_kwh",
      "Voltage: simulator.voltage",
      "Power Factor: simulator.power_factor",
    ],
  };
}

function buildDefaultForm(state: LocationState): EnergyPointMappingRequest {
  const protocol = cleanProtocol(state.protocol);
  const points = getDefaultPoints(protocol);

  return {
    protocol,
    externalDeviceId: state.externalDeviceId || "em-main-01",
    meterName: state.meterName || "Main Incoming Energy Meter",
    activePowerKwPoint: points.activePowerKwPoint,
    totalEnergyKwhPoint: points.totalEnergyKwhPoint,
    voltagePoint: points.voltagePoint,
    currentAmpPoint: points.currentAmpPoint,
    powerFactorPoint: points.powerFactorPoint,
    frequencyHzPoint: points.frequencyHzPoint,
    baselinePowerKw: 10,
    ratedPowerKw: 20,
    enabled: true,
  };
}

function responseToForm(
  response: EnergyPointMappingResponse,
  fallback: EnergyPointMappingRequest
): EnergyPointMappingRequest {
  return {
    protocol: cleanProtocol(response.protocol || fallback.protocol),
    externalDeviceId: response.externalDeviceId || fallback.externalDeviceId,
    meterName: response.meterName || fallback.meterName,
    activePowerKwPoint: response.activePowerKwPoint ?? fallback.activePowerKwPoint,
    totalEnergyKwhPoint:
      response.totalEnergyKwhPoint ?? fallback.totalEnergyKwhPoint,
    voltagePoint: response.voltagePoint ?? fallback.voltagePoint,
    currentAmpPoint: response.currentAmpPoint ?? fallback.currentAmpPoint,
    powerFactorPoint: response.powerFactorPoint ?? fallback.powerFactorPoint,
    frequencyHzPoint: response.frequencyHzPoint ?? fallback.frequencyHzPoint,
    baselinePowerKw: response.baselinePowerKw ?? fallback.baselinePowerKw,
    ratedPowerKw: response.ratedPowerKw ?? fallback.ratedPowerKw,
    enabled: response.enabled ?? fallback.enabled,
  };
}

export default function EnergyMeterPointMappingPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const { tenantId, siteId, energyMeterId } = useParams();

  const routeState = (location.state || {}) as LocationState;

  const resolvedTenantId = tenantId ?? "";
  const resolvedSiteId = siteId ?? "";
  const resolvedEnergyMeterId = energyMeterId ?? "";

  const defaultForm = useMemo(
    () => buildDefaultForm(routeState),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [routeState.meterName, routeState.externalDeviceId, routeState.protocol]
  );

  const [form, setForm] = useState<EnergyPointMappingRequest>(defaultForm);
  const [existing, setExisting] = useState<EnergyPointMappingResponse | null>(
    null
  );

  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  const currentProtocol = cleanProtocol(form.protocol);
  const protocolInfo = getProtocolInfo(currentProtocol);

  const pointMappingUrl = `/api/energy/tenants/${resolvedTenantId}/sites/${resolvedSiteId}/meters/${resolvedEnergyMeterId}/point-mapping`;

  const glassButton =
  "inline-flex items-center gap-2 rounded-2xl border border-white/10 bg-white/10 px-4 py-2 text-sm font-medium text-slate-100 shadow-lg shadow-black/20 backdrop-blur-xl transition hover:bg-white/15";

  useEffect(() => {
    if (!resolvedTenantId || !resolvedSiteId || !resolvedEnergyMeterId) {
      setErrorMessage("Missing tenant, site, or energy meter id.");
      setLoading(false);
      return;
    }

    void loadPointMapping();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [resolvedTenantId, resolvedSiteId, resolvedEnergyMeterId]);

  function updateField<K extends keyof EnergyPointMappingRequest>(
    key: K,
    value: EnergyPointMappingRequest[K]
  ) {
    setForm((prev) => ({
      ...prev,
      [key]: value,
    }));
  }

  function applyProtocolTemplate(nextProtocolValue: string) {
    const nextProtocol = cleanProtocol(nextProtocolValue);
    const points = getDefaultPoints(nextProtocol);

    setForm((prev) => ({
      ...prev,
      protocol: nextProtocol,
      ...points,
    }));

    setSuccessMessage(
      `${nextProtocol} template applied. Review point references before saving.`
    );

    window.setTimeout(() => {
      setSuccessMessage(null);
    }, 2500);
  }

  async function loadPointMapping() {
    setLoading(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      const data = await api<EnergyPointMappingResponse | null>(pointMappingUrl, {
        method: "GET",
      });

      if (!data) {
        setExisting(null);
        setForm(defaultForm);
        return;
      }

      setExisting(data);
      setForm(responseToForm(data, defaultForm));
    } catch (error: any) {
      const status = error?.status || error?.response?.status;

      if (status === 204 || status === 404) {
        setExisting(null);
        setForm(defaultForm);
        return;
      }

      setErrorMessage(
        error?.response?.data?.message ||
          error?.message ||
          "Failed to load Energy Meter point mapping."
      );
    } finally {
      setLoading(false);
    }
  }

  async function savePointMapping() {
    setSaving(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      const saved = await api<EnergyPointMappingResponse>(pointMappingUrl, {
        method: "PUT",
        body: JSON.stringify(form),
      });

      setExisting(saved);
      setForm(responseToForm(saved, form));
      setSuccessMessage("Energy Meter point mapping saved successfully.");
    } catch (error: any) {
      setErrorMessage(
        error?.response?.data?.message ||
          error?.message ||
          "Failed to save Energy Meter point mapping."
      );
    } finally {
      setSaving(false);
    }
  }

  async function createSimulatorDefaults() {
    const points = getDefaultPoints("SIMULATOR");

    const simulatorForm: EnergyPointMappingRequest = {
      ...form,
      protocol: "SIMULATOR",
      ...points,
      baselinePowerKw: form.baselinePowerKw ?? 10,
      ratedPowerKw: form.ratedPowerKw ?? 20,
      enabled: true,
    };

    setForm(simulatorForm);
    setSaving(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      const saved = await api<EnergyPointMappingResponse>(pointMappingUrl, {
        method: "PUT",
        body: JSON.stringify(simulatorForm),
      });

      setExisting(saved);
      setForm(responseToForm(saved, simulatorForm));
      setSuccessMessage("Simulator point defaults saved successfully.");
    } catch (error: any) {
      setErrorMessage(
        error?.response?.data?.message ||
          error?.message ||
          "Failed to save simulator defaults."
      );
    } finally {
      setSaving(false);
    }
  }

  async function deletePointMapping() {
    if (!window.confirm("Delete point mapping for this Energy Meter?")) {
      return;
    }

    setSaving(true);
    setErrorMessage(null);
    setSuccessMessage(null);

    try {
      await api<void>(pointMappingUrl, {
        method: "DELETE",
      });

      setExisting(null);
      setForm(defaultForm);
      setSuccessMessage("Energy Meter point mapping deleted.");
    } catch (error: any) {
      setErrorMessage(
        error?.response?.data?.message ||
          error?.message ||
          "Failed to delete Energy Meter point mapping."
      );
    } finally {
      setSaving(false);
    }
  }

  const pointRows: Array<{
    label: string;
    field: keyof EnergyPointMappingRequest;
    simulator: string;
    bacnet: string;
    modbus: string;
    hint: string;
  }> = [
    {
      label: "Active Power kW",
      field: "activePowerKwPoint",
      simulator: "simulator.active_power_kw",
      bacnet: "analogInput:1",
      modbus: "inputRegister:30001:float32",
      hint: "Live demand/load value",
    },
    {
      label: "Total Energy kWh",
      field: "totalEnergyKwhPoint",
      simulator: "simulator.total_energy_kwh",
      bacnet: "analogInput:2",
      modbus: "inputRegister:30003:float32",
      hint: "Cumulative imported energy",
    },
    {
      label: "Voltage",
      field: "voltagePoint",
      simulator: "simulator.voltage",
      bacnet: "analogInput:3",
      modbus: "inputRegister:30005:float32",
      hint: "Supply voltage",
    },
    {
      label: "Current Amp",
      field: "currentAmpPoint",
      simulator: "simulator.current_amp",
      bacnet: "analogInput:4",
      modbus: "inputRegister:30007:float32",
      hint: "Measured current",
    },
    {
      label: "Power Factor",
      field: "powerFactorPoint",
      simulator: "simulator.power_factor",
      bacnet: "analogInput:5",
      modbus: "inputRegister:30009:float32",
      hint: "0.00 to 1.00",
    },
    {
      label: "Frequency Hz",
      field: "frequencyHzPoint",
      simulator: "simulator.frequency_hz",
      bacnet: "analogInput:6",
      modbus: "inputRegister:30011:float32",
      hint: "Usually around 50Hz in NZ",
    },
  ];

  function placeholderFor(row: (typeof pointRows)[number]) {
    if (currentProtocol === "BACNET") return row.bacnet;
    if (currentProtocol === "MODBUS") return row.modbus;
    return row.simulator;
  }

  if (loading) {
    return (
      <PageShell>
        <div className="flex min-h-[60vh] items-center justify-center">
          <div className="rounded-3xl border border-white/10 bg-white/6 p-8 shadow-2xl shadow-cyan-500/10 backdrop-blur-2xl">
            <Loader2 className="mx-auto h-9 w-9 animate-spin text-cyan-200" />
            <p className="mt-4 text-sm text-slate-300">
              Loading Energy Meter point mapping...
            </p>
          </div>
        </div>
      </PageShell>
    );
  }

  return (
    <PageShell>
      <main className="relative z-10 px-5 py-6 pb-12 md:px-8 lg:px-10">
        <div className="mb-5">
        <button
          type="button"
          onClick={() =>
            navigate(
              `/admin/tenants/${resolvedTenantId}/sites/${resolvedSiteId}/energy/mapping`
            )
          }
          className={glassButton}
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Energy Mapping
        </button>
      </div>
        <motion.section
          initial={{ opacity: 0, y: 18, scale: 0.99 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          transition={{ duration: 0.38, ease: [0.22, 1, 0.36, 1] }}
          className="rounded-3xl border border-white/10 bg-white/[0.07] p-6 shadow-2xl shadow-cyan-500/10 backdrop-blur-2xl"
        >
          <div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between">
            <div>
              <div className="flex items-center gap-3">
                <div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/10 p-3 text-cyan-100">
                  <DatabaseZap className="h-6 w-6" />
                </div>

                <div>
                  <p className="text-xs uppercase tracking-[0.35em] text-cyan-200/70">
                    QbitLabs BMS Energy Mapping
                  </p>
                  <h1 className="mt-1 text-2xl font-bold text-white md:text-3xl">
                    Energy Meter Point Mapping
                  </h1>
                </div>
              </div>

              <p className="mt-4 max-w-3xl text-sm leading-6 text-slate-300">
                Configure how the Python Edge Controller reads simulator,
                BACnet, or Modbus points for this production Energy Meter.
              </p>

              <div className="mt-4 grid gap-2 text-xs text-slate-400 md:grid-cols-3">
                <div>
                  <span className="text-slate-200">Meter:</span>{" "}
                  {form.meterName}
                </div>
                <div>
                  <span className="text-slate-200">External Device:</span>{" "}
                  {form.externalDeviceId}
                </div>
                <div>
                  <span className="text-slate-200">Energy Meter ID:</span>{" "}
                  {resolvedEnergyMeterId}
                </div>
              </div>
            </div>

            <div className="flex flex-wrap gap-3">
              <button
                type="button"
                onClick={() =>
                  navigate(
                    `/admin/tenants/${resolvedTenantId}/sites/${resolvedSiteId}/energy/mapping`
                  )
                }
                className="inline-flex items-center gap-2 rounded-2xl border border-white/10 bg-white/10 px-4 py-3 text-sm font-semibold text-slate-100 transition hover:bg-white/15"
              >
                <ArrowLeft className="h-4 w-4" />
                Back to Mapping
              </button>

              <button
                type="button"
                onClick={() => void loadPointMapping()}
                disabled={saving}
                className="inline-flex items-center gap-2 rounded-2xl border border-cyan-300/20 bg-cyan-300/10 px-4 py-3 text-sm font-semibold text-cyan-100 transition hover:bg-cyan-300/20 disabled:opacity-60"
              >
                <RefreshCw className="h-4 w-4" />
                Reload
              </button>
            </div>
          </div>
        </motion.section>

        {errorMessage && (
          <MessageBox type="error" icon={<AlertCircle className="h-4 w-4" />}>
            {errorMessage}
          </MessageBox>
        )}

        {successMessage && (
          <MessageBox
            type="success"
            icon={<CheckCircle2 className="h-4 w-4" />}
          >
            {successMessage}
          </MessageBox>
        )}

        <section className="mt-6 rounded-3xl border border-cyan-300/15 bg-cyan-300/[0.07] p-5 shadow-2xl shadow-cyan-500/10 backdrop-blur-2xl">
          <div className="flex items-start gap-3">
            <div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/10 p-3 text-cyan-100">
              <Sparkles className="h-5 w-5" />
            </div>

            <div>
              <h2 className="text-lg font-semibold text-white">
                {protocolInfo.title}
              </h2>
              <p className="mt-1 text-sm text-slate-300">
                {protocolInfo.description}
              </p>

              <div className="mt-4 grid gap-2 text-xs text-slate-400 md:grid-cols-2">
                {protocolInfo.examples.map((example) => (
                  <div
                    key={example}
                    className="rounded-2xl border border-white/10 bg-slate-950/50 px-3 py-2"
                  >
                    {example}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section className="mt-6 rounded-3xl border border-white/10 bg-white/6 p-5 shadow-2xl shadow-cyan-500/10 backdrop-blur-2xl">
          <div className="grid gap-4 md:grid-cols-4">
            <Field label="Meter Name">
              <input
                value={form.meterName}
                onChange={(event) => updateField("meterName", event.target.value)}
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition focus:border-cyan-400/60"
              />
            </Field>

            <Field label="External Device ID">
              <input
                value={form.externalDeviceId}
                onChange={(event) =>
                  updateField("externalDeviceId", event.target.value)
                }
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition focus:border-cyan-400/60"
              />
            </Field>

            <Field label="Protocol">
              <select
                value={currentProtocol}
                onChange={(event) => applyProtocolTemplate(event.target.value)}
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition focus:border-cyan-400/60"
              >
                <option value="SIMULATOR">SIMULATOR</option>
                <option value="BACNET">BACNET</option>
                <option value="MODBUS">MODBUS</option>
              </select>
            </Field>

            <label className="mt-6 flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-200">
              <input
                type="checkbox"
                checked={Boolean(form.enabled)}
                onChange={(event) => updateField("enabled", event.target.checked)}
              />
              Enabled
            </label>
          </div>

          <div className="mt-5 grid gap-4 md:grid-cols-2">
            <Field label="Baseline Power kW">
              <input
                type="number"
                step="0.001"
                value={form.baselinePowerKw ?? ""}
                onChange={(event) =>
                  updateField(
                    "baselinePowerKw",
                    event.target.value === "" ? null : Number(event.target.value)
                  )
                }
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition focus:border-cyan-400/60"
              />
            </Field>

            <Field label="Rated Power kW">
              <input
                type="number"
                step="0.001"
                value={form.ratedPowerKw ?? ""}
                onChange={(event) =>
                  updateField(
                    "ratedPowerKw",
                    event.target.value === "" ? null : Number(event.target.value)
                  )
                }
                className="mt-2 w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition focus:border-cyan-400/60"
              />
            </Field>
          </div>

          <div className="mt-6 overflow-x-auto rounded-3xl border border-white/10">
            <table className="min-w-full border-separate border-spacing-0">
              <thead>
                <tr className="bg-white/5 text-left text-sm text-slate-300">
                  <th className="px-4 py-3 font-semibold">Energy Field</th>
                  <th className="px-4 py-3 font-semibold">Source Point Ref</th>
                  <th className="px-4 py-3 font-semibold">Note</th>
                </tr>
              </thead>

              <tbody>
                {pointRows.map((row, index) => (
                  <tr
                    key={row.field}
                    className={index % 2 === 0 ? "bg-slate-950/10" : "bg-white/5"}
                  >
                    <td className="px-4 py-3 text-sm font-medium text-slate-100">
                      {row.label}
                    </td>

                    <td className="px-4 py-3">
                      <input
                        value={String(form[row.field] ?? "")}
                        onChange={(event) =>
                          updateField(row.field, event.target.value as any)
                        }
                        placeholder={placeholderFor(row)}
                        className="w-full rounded-2xl border border-white/10 bg-slate-950 px-3 py-2 text-sm text-white outline-none transition placeholder:text-slate-600 focus:border-cyan-400/60"
                      />
                    </td>

                    <td className="px-4 py-3 text-xs text-slate-400">
                      {row.hint}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="mt-6 flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div className="text-xs text-slate-500">
              {existing ? (
                <span>
                  Existing mapping found. Config version:{" "}
                  <span className="text-slate-300">
                    {existing.configVersion ?? "-"}
                  </span>
                </span>
              ) : (
                <span>No point mapping saved yet.</span>
              )}
            </div>

            <div className="flex flex-wrap gap-3">
              {currentProtocol === "SIMULATOR" && (
                <button
                  type="button"
                  onClick={() => void createSimulatorDefaults()}
                  disabled={saving}
                  className="inline-flex items-center gap-2 rounded-2xl border border-cyan-400/30 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-200 transition hover:bg-cyan-500/20 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  <Sparkles className="h-4 w-4" />
                  Simulator Defaults
                </button>
              )}

              {existing && (
                <button
                  type="button"
                  onClick={() => void deletePointMapping()}
                  disabled={saving}
                  className="inline-flex items-center gap-2 rounded-2xl border border-rose-400/30 bg-rose-500/10 px-4 py-2 text-sm font-semibold text-rose-200 transition hover:bg-rose-500/20 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  <Trash2 className="h-4 w-4" />
                  Delete Points
                </button>
              )}

              <button
                type="button"
                onClick={() => void savePointMapping()}
                disabled={saving}
                className="inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-blue-500 to-purple-500 px-5 py-2 text-sm font-semibold text-white transition hover:scale-[1.02] disabled:cursor-not-allowed disabled:opacity-60"
              >
                {saving ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Save className="h-4 w-4" />
                )}
                {saving ? "Saving..." : "Save Mapping"}
              </button>
            </div>
          </div>
        </section>
      </main>
    </PageShell>
  );
}

function PageShell({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100">
      <div className="pointer-events-none fixed inset-0">
        <div className="absolute left-[-10%] top-[-10%] h-80 w-80 rounded-full bg-cyan-500/20 blur-3xl" />
        <div className="absolute right-[-10%] top-[20%] h-96 w-96 rounded-full bg-violet-500/20 blur-3xl" />
        <div className="absolute bottom-[-15%] left-[25%] h-96 w-96 rounded-full bg-emerald-500/10 blur-3xl" />
      </div>
      {children}
    </div>
  );
}

function Field({
  label,
  children,
}: {
  label: string;
  children: ReactNode;
}) {
  return (
    <label className="block">
      <span className="text-xs font-medium uppercase tracking-wider text-slate-400">
        {label}
      </span>
      {children}
    </label>
  );
}

function MessageBox({
  type,
  icon,
  children,
}: {
  type: "error" | "success";
  icon: ReactNode;
  children: ReactNode;
}) {
  const cls =
    type === "error"
      ? "border-rose-300/20 bg-rose-500/10 text-rose-100 shadow-rose-500/10"
      : "border-emerald-300/20 bg-emerald-500/10 text-emerald-100 shadow-emerald-500/10";

  return (
    <div
      className={`mt-5 flex items-start gap-3 rounded-3xl border p-4 text-sm shadow-2xl backdrop-blur-2xl ${cls}`}
    >
      <div className="mt-0.5 shrink-0">{icon}</div>
      <div>{children}</div>
    </div>
  );
}